### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by aovertus** [upmysport/onesignal#29]
Hi, 

have you any ideas about a release date ? 

Thanks for your awesome work !

**Comment by pvcarrera** [comment]
Hi, I'm really please and surprised that someone is asking for a release date, it looks like I have a potential user :smile: 

My initial idea was to publish it in RubyGems once I cover the main OneSignal operations, right now this gem only supports `add_device` and `notify`. But since I work on this project mainly in my spare time, I don't have a release date.

BTW PRs are more than welcome
